version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8080"
    depends_on:
      - mysql

  driver-service:
    build: ./driver-service
    ports:
      - "8082:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cabdb
    ports:
      - "3306:3306"
